package com.clover.tr34.samples;

/**
 * Sample messages for test that correspond to the certificates and keys found
 * in {@link CloverSampleTr34KeyStoreData}.
 */
public final class CloverSampleTr34Messages {

    /**
     * Generated by Clover client.
     */
    public static final String CT_KRD_Pem =
            "-----BEGIN TR34 KRD CREDENTIAL TOKEN-----\n" +
            "MIIDnwYJKoZIhvcNAQcCoIIDkDCCA4wCAQExADALBgkqhkiG9w0BBwGgggN0MIID\n" +
            "cDCCAligAwIBAgIQbCpMOGMtYO46ksi7B0ziSTANBgkqhkiG9w0BAQsFADBTMQsw\n" +
            "CQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2VvczEg\n" +
            "MB4GA1UEAxMXVEVTVCBDbG92ZXIgVFIzNCBLUkQgQ0EwHhcNMjMwOTAxMjIwNjUw\n" +
            "WhcNMzgwODE0MjIwMDA5WjBSMQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVy\n" +
            "MREwDwYDVQQLEwhkZXZpY2VvczEfMB0GA1UEAxMWVEVTVCBDbG92ZXIgVFIzNCBL\n" +
            "UkQgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALhilgrs5YCtDSiW\n" +
            "a/Z/TX96qztN0dLlyh7rYimeBkEpEU4kJwWogRrt6CGIQ1+guSZLm4QtqWznbR72\n" +
            "bDSJHLArnWi+Dx+9AHMK1AaZUrf75eC/yh5yV/sI0YFmnWp4DjV0AtGKgzDmcjgQ\n" +
            "loIR2zrUrPXihXSUcwxJe0q/IqrMEdQ+morvZ2w+8Vlo1WszyvknhrCUWzKgzf9D\n" +
            "Z+9BG1fKREffS2SUruBHCFkQeXDFdP3d1RtgZznWGXQhwUXa5jkoFkR4jQYKR8Lh\n" +
            "j8v9YEbWcG8L7lOMkCZfRWeGzuQnjKRS9bx6D67gxvY2XJLbmfov4HNVkdxSO68x\n" +
            "Ed8qI6UCAwEAAaNBMD8wDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwHwYD\n" +
            "VR0jBBgwFoAU11VYe+bdyaYUH4MF8MFoJvdaOFkwDQYJKoZIhvcNAQELBQADggEB\n" +
            "AKdiYCU87sxKtldqs+4bNrSIXEwc/6XKCG2nCCToGNYOE2FApDWBZcOUcSEdLp0n\n" +
            "7FEa/gLWVr5J/EOUkDp+5gAgmtbyvHptla8ThxVWPFHCXXbo4qlylfFwcXF1OG8I\n" +
            "+mwggUSh9DFoq27JUJApjaDcVyQ2Ywvdq0EcITYgrrZKZrqD7JYTEYmVXtKqB409\n" +
            "1HxtSM9vWophBudJDfK308x9fj+PM6AZqWRG7XCMShi3tVERiImTw0Pqn2/PK0aE\n" +
            "afxpvTRJh0kjsujX4HteBGXzLjjikfyjJKGz6Fyl5A8T9VAEFObqqZQ6Sa92wMMs\n" +
            "9Ow1xNvbr1cGImewoVhyBJUxAA==\n" +
            "-----END TR34 KRD CREDENTIAL TOKEN-----";

}
