package com.clover.tr34.samples;

import com.clover.tr34.Tr34CryptoUtils;
import com.clover.tr34.Tr34KdhRevocation;
import com.clover.tr34.Tr34KeyStoreData;
import com.clover.tr34.Tr34ScdKeyStoreData;

import java.math.BigInteger;
import java.security.PrivateKey;
import java.security.cert.CRLReason;
import java.security.cert.X509Certificate;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

/**
 * Sample TR-34 keys and certificates generated by Clover for test and development purposes.
 * <p>
 * The hierarchy is the simplest possible form: one KRD CA and one KDH CA with no additional
 * intermediate certificates. As mandated by TR-34 the KRD CA and KDH CA and signed by a single
 * root certificate which leads to he unfortunately side effect that a KRD and KDH are not
 * distinguishable by their root certificate.
 */
public final class CloverSampleTr34KeyStoreData extends Tr34KeyStoreData {

    static final String TR34_Root_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDdDCCAlygAwIBAgIQTq9Hb668e0nzTs0Y45MgBTANBgkqhkiG9w0BAQsFADBU\n" +
            "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2Vv\n" +
            "czEhMB8GA1UEAxMYVEVTVCBDbG92ZXIgVFIzNCBSb290IENBMB4XDTIzMDkwMTIy\n" +
            "MDAwOVoXDTM4MDgyODIyMDAwOVowVDELMAkGA1UEBhMCVVMxDzANBgNVBAoTBkNs\n" +
            "b3ZlcjERMA8GA1UECxMIZGV2aWNlb3MxITAfBgNVBAMTGFRFU1QgQ2xvdmVyIFRS\n" +
            "MzQgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANeeAxCc\n" +
            "XTnUkxgp2UN5mZHS7sv3KaJ7iWqo16KxHlAKpC+DaN1e+fSFaXlI6tWs9VWqDuuv\n" +
            "H8xBUAoIWaPE/Rm7trgmYNjKtCs2v2QLAsq6rzfo1v3SjO9DjuiuZt9W7BpqTAOb\n" +
            "fzNXMb/W0gwL9cRn6Y9bMioumnW+Emhou3u4pU3wxIrt3zjqpQ2MhYBadWBb1ZtF\n" +
            "919NgI7H91MntGVrOOoteXPSK3ygWowJ2K7qgfT37pX13N1duZserHWZXjNU7GuC\n" +
            "NoNDnatnxBKRnoQLc3G47gNSVr6PGA0T4PzE/8j/S+OV2kLTU7JFQoPi7hXUHeCw\n" +
            "D0a1yiUVDzF8B+0CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF\n" +
            "MAMBAf8wHQYDVR0OBBYEFEnohVQIi1LkEJlHSASkhosTKgiJMA0GCSqGSIb3DQEB\n" +
            "CwUAA4IBAQBOLLkBLVfa8cggTa4gx5WCKSucNM/1t81fC15r6B0/VjUPwKrRpd+T\n" +
            "akwsJ3ScjSOWk6rfWjzaXQMJfH5cKj2bmnSLPKYnVnX0UiWlckVKTGhl7oK1+eWE\n" +
            "QvZmPKD6oRKcsXjmi6E2ZdJEb0HzEm78eoa2Q61sCmL+aKVPBtctUuPrD84ETxd9\n" +
            "hNRdrzXGVJesg58q4ULGwd9qC/6eMDYbHX17E2Lf2XwM9/Aq6ITNlv8/fcBYIFPy\n" +
            "AVjPD+QqayNyC5LsLRGi9a76h8FDVHHKpMxg3vxbtiXIJ7Hg5vPrQWcFOpj1HQyC\n" +
            "L4aXPicIuSyrg3b8M1WSp24bJkMptmhj\n" +
            "-----END CERTIFICATE-----";

    static final String TR34_Root_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEowIBAAKCAQEA154DEJxdOdSTGCnZQ3mZkdLuy/cponuJaqjXorEeUAqkL4No\n" +
            "3V759IVpeUjq1az1VaoO668fzEFQCghZo8T9Gbu2uCZg2Mq0Kza/ZAsCyrqvN+jW\n" +
            "/dKM70OO6K5m31bsGmpMA5t/M1cxv9bSDAv1xGfpj1syKi6adb4SaGi7e7ilTfDE\n" +
            "iu3fOOqlDYyFgFp1YFvVm0X3X02Ajsf3Uye0ZWs46i15c9IrfKBajAnYruqB9Pfu\n" +
            "lfXc3V25mx6sdZleM1Tsa4I2g0Odq2fEEpGehAtzcbjuA1JWvo8YDRPg/MT/yP9L\n" +
            "45XaQtNTskVCg+LuFdQd4LAPRrXKJRUPMXwH7QIDAQABAoIBAQCcrGejuUsQi4N6\n" +
            "6mXB3ukVCgWU1fs94rBefWN7B2J0XNci40TennXYFN0oUTC6pRv77D89SJo9bDQB\n" +
            "pkGke65B9aF2vARhYyF5ySVXR5z2vKI3aQxXkZfw/9EnCBseLGYRZ63mbSYHo1M2\n" +
            "B53HPSWPWsZe8bBI8GYyKjPsBDY/Vf3uvgEnS7MeGqiXTtpBo0WBPrXcbu5GWO+/\n" +
            "ujmUyB7FWE2V+venTxP4vsDngtcrdhdw07K+vYlE6GWFsne44VT9qI9c3Qqs/QZ5\n" +
            "M2pzuuV9dm6nkZVTk4frI0FXh4H7n3Ir08qtw8pmQbms4nRXHorfluWgMnwOO/MN\n" +
            "Vn7MXzFNAoGBAOmpCDMin9AgWjb3Q6t6lllJLxbWqF5mLv3eergOhDS3dvEQIIIw\n" +
            "7HmHaoVnpcHXKVhHJZwgvjWzy3dD1ctxQGi/qxN0vTzpoy8uHKG6efyFHOjEFnD3\n" +
            "8uB3DiNvVQEDoXvDXow+pfbZ80PCPRZbYdt+j5gS84eQQvzHpK7sNMyTAoGBAOw7\n" +
            "XbpxzKElbJuDN4yisscG267ooQuEzANlvATP1dhnfPRx7JhKk0cOWVHq/sHrg7Z5\n" +
            "+g/qA/Q86Oi1x7qfDSfWy5X2nII0MVVQPVufTErxo06ammojDzGQACTWjWH5l+cG\n" +
            "uCsMo4Ij2t0/Ab3p/Wi4jkQ2mIb0ypTvE58ivSl/AoGANRdWKKBGZbjkJrcaJh1t\n" +
            "ig4J6AuQKBrZtI9XnPiXa48ANJfwewR4xshRGMzLKfckis1nq0j5TyRyJ8A/FMG/\n" +
            "280pJvuQgAWqMW8tzEWdsBXi0rSzUKnWAtCqYrzKOLfFemSS2BToCuXM02mQDcNn\n" +
            "wcLJB8nOkc/imKMYNTKwcIcCgYAFpuX3MAHVWS/gCKOrmbjtShy3cplnzSWUbzqw\n" +
            "YsibBN7YemFOw3oCmTVJ4HV37kqYcxKojtDJZyurZa4BqQyHh3wXem8ELnt/rwvI\n" +
            "xWbt5BokJ07Ke0xBw1A9kWSQk4gu3tpJLWQ8GN+Dq54/DPojJ0dAGo5LrE+sgIvX\n" +
            "ot0jwQKBgAlCkynsA1AeyuPZ/G7LXKzAGuCYZinDvrOwtpWNr0nQ/Ssj7UN9kg0/\n" +
            "rBCqZ+f3Nt3v8Scw9qwdEt7toemTKMgFr2UHa50tgFW01kcy8anAAJLO9CDgKIsz\n" +
            "T8hE9bnM3CWl4E/8jNCw3tIx8+xQruGZZ3GB8XsIWML2xzVziBaT\n" +
            "-----END RSA PRIVATE KEY-----";

    static final String TR34_KDH_CA_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDlDCCAnygAwIBAgIQTqak5H7dM9yiy3fI6yraoDANBgkqhkiG9w0BAQsFADBU\n" +
            "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2Vv\n" +
            "czEhMB8GA1UEAxMYVEVTVCBDbG92ZXIgVFIzNCBSb290IENBMB4XDTIzMDkwMTIy\n" +
            "MDAzN1oXDTM4MDgyMTIyMDAwOVowUzELMAkGA1UEBhMCVVMxDzANBgNVBAoTBkNs\n" +
            "b3ZlcjERMA8GA1UECxMIZGV2aWNlb3MxIDAeBgNVBAMTF1RFU1QgQ2xvdmVyIFRS\n" +
            "MzQgS0RIIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqH8jmFXC\n" +
            "FXIfo9EMWcvo6NDDkxtkSUwFV9T/ONkqEzydA16p/+Ja5+ythXTvXjMWXjfCpg76\n" +
            "83QSRASq2CV7VXIMAG/YosQWlbDTIniYcJn9naMBUoIIQ4nw6Hxs4x4X3IOi0c/+\n" +
            "80UIxd3lCuSh3Y6iDs08BUfe1g7XI0JGUrdEjL3VVD14N3fSNCxLiwsmbhcMjPPe\n" +
            "KpJdZB9rXpuxybHhvy1fyktOe+sXl+j+T5AfD3gbWjSQJfC5ylOS2b5jz56cO51c\n" +
            "T8RK/UWGHR4hwbiF+Of+HJKU6ZDLcDQ1XmUL1RC6c8QKW/Ziha5sbxlxmspendqR\n" +
            "ZQOLtLbTgTh4sQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUw\n" +
            "AwEB/zAdBgNVHQ4EFgQUbeIyuJDjaE5J/WjddKCtqKMCQ4wwHwYDVR0jBBgwFoAU\n" +
            "SeiFVAiLUuQQmUdIBKSGixMqCIkwDQYJKoZIhvcNAQELBQADggEBAJ36O4R+sbAz\n" +
            "GResQmn66zoI+0OR0rHZbGvW5b/fjllGtn4L4CoyH+1VkOtBv+HEswGu/3Q4Chfg\n" +
            "Mo/rAX2gIHPqQhKlmETC/4wcSFp+ml6VC1exfsYjWggoWQ17NigRh8TMFBDHmxE+\n" +
            "PsdsKf8vzRYw603OYpAPKPiRotzCsMS25EGw+LbzT4C3peNQSz7DKWRB4Ynk6fj6\n" +
            "OPzWWOMHAtSufVQ1VUqUAqjxRbi78ze/iJf31cpTjw9IJUhRMZdYIHv6okM64QbH\n" +
            "HaewJPOBdsbwk+6A/6RT//gilj2i6SlIo3yAjvzFTWCeOPvgxI0pUV+DGCWSRHki\n" +
            "zqoixiFihpE=\n" +
            "-----END CERTIFICATE-----";

    static final String TR34_KDH_CA_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEpQIBAAKCAQEAqH8jmFXCFXIfo9EMWcvo6NDDkxtkSUwFV9T/ONkqEzydA16p\n" +
            "/+Ja5+ythXTvXjMWXjfCpg7683QSRASq2CV7VXIMAG/YosQWlbDTIniYcJn9naMB\n" +
            "UoIIQ4nw6Hxs4x4X3IOi0c/+80UIxd3lCuSh3Y6iDs08BUfe1g7XI0JGUrdEjL3V\n" +
            "VD14N3fSNCxLiwsmbhcMjPPeKpJdZB9rXpuxybHhvy1fyktOe+sXl+j+T5AfD3gb\n" +
            "WjSQJfC5ylOS2b5jz56cO51cT8RK/UWGHR4hwbiF+Of+HJKU6ZDLcDQ1XmUL1RC6\n" +
            "c8QKW/Ziha5sbxlxmspendqRZQOLtLbTgTh4sQIDAQABAoIBAQCDG+Ljnx9VNqcd\n" +
            "/gVBPiRuPDtiFTdUvV2O+YLahkhyDYETZS6cmFIqEwT2SoYTY2ctSvAf7Joio5eu\n" +
            "637Qj2HHm+Vw1ZbZGAGG2r9/HB1pyLkKVxMpU1sAyq31CRRlKT5h7N/dqJ32RypL\n" +
            "ZJzbfAnjbx/0qofgiAsBvyxyGBjGNOc0BLZLa7fIOVcq+G+SjPuWFFy3ehCcoko+\n" +
            "bW+zl8/21x1E8VEy4R0ftEMqsehFpUIV8Fbgj4yp+S1j6aFZ/kJqX6PdxbIyaVaf\n" +
            "UTGrLThHKaqYZWSXzgEv+M7e2nwBEwnUDl3KUchxsFSzNFY6zvTlT12s2xTIKa2m\n" +
            "gYKU5tXBAoGBANaOSHlshAdrDm/UJCREr7mTJZdpdrXQMKv7s0p0QRQp/loSms+N\n" +
            "+Fl35Sv7mdVyQCRJu2o5lGAto5y6YBe34NHBAcYwDU3fRBrDUfVQM6ZukSkQKgRC\n" +
            "0lWVYzv8hQBjyX2YxmlH1cGbflJ0Zf3KfVzxQOure/r4RR85Ej2R4AVJAoGBAMkL\n" +
            "PrvVZqShnVxE5SplvCgmXEQoh7l4ePta+utuX//ecnbC2AAwGoLVntK9wLRUhF2c\n" +
            "tziOIIUksdwunR+32RSclK6pEMblwKVz1D7Llg+7a+iZH5TzWwHOv65jL8Mro4SZ\n" +
            "+XQ+XJohW6l/yQKE9P+KljCqTqKynH0jhO76uqApAoGBAMQaxnldSwvwuQBTmTkh\n" +
            "IrBuozRSa/NgN6xqYYSS34zLmTTAvokozS8RXAEodYHXbHL+hXNg75I9BMdSvlPP\n" +
            "eIifbby03OQpRnljvzyGMr9TXhB3OsAsR018PnhspTAnBNpsUiWWR/Uu53X79+DR\n" +
            "PGZACEOfuLE6TQttwZNPCsApAoGBAKEnyHPdDlhtzKxH9cNUpc0xYsioDJQaBDDI\n" +
            "r1bFtWJvuCWG7orIBJhYEOYxgSWMkkZP93b4Rw0zavdqzjy8rOCe23hewboONazq\n" +
            "+noTzAh0Xn2nMO+/W3ZJetGZZJH4iy0iGBqcWrKahtWKP2ErnxCw0M/V1Q8KSfLt\n" +
            "5AOFLNBxAoGAHmCkNBjctPfG9Sl2/Tud2ERYiNZimSLdKn3UnOpY9W8Y97r6SBtP\n" +
            "qj8vDbVrhPwudEz8GfXsbUmwxP9LLqXndjURAosAtE79cdSckJETRbnAJBpZ756R\n" +
            "CDeQuo9S44CIbt0B9EfcGGN1uWKEsrfm7NdAWny5WH83y9T6jPsKOcQ=\n" +
            "-----END RSA PRIVATE KEY-----";

    public static final String TR34_KRD_CA_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDlDCCAnygAwIBAgIQHIcewFfOHCCMjreEjAm3HDANBgkqhkiG9w0BAQsFADBU\n" +
            "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2Vv\n" +
            "czEhMB8GA1UEAxMYVEVTVCBDbG92ZXIgVFIzNCBSb290IENBMB4XDTIzMDkwMTIy\n" +
            "MDY0N1oXDTM4MDgyMTIyMDAwOVowUzELMAkGA1UEBhMCVVMxDzANBgNVBAoTBkNs\n" +
            "b3ZlcjERMA8GA1UECxMIZGV2aWNlb3MxIDAeBgNVBAMTF1RFU1QgQ2xvdmVyIFRS\n" +
            "MzQgS1JEIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzSvOA0+t\n" +
            "J/h2/6mZQw/s/WckpTEu6dAmi9LqtaAZMdT+0bjcPYKpLSFJ8l0p0lLOiv6OsEVd\n" +
            "n7kb+N5hCOpsnV1gWW1L57VSpIdBlqdPD6PggUPslu+9gxDDbyCIrvET36W628Q2\n" +
            "Q+nGwZV1muRU81SuR6G8Wopk2nruqLlTcR3+cnv683eQdsYvvq4mH0+wL4Sc3Se/\n" +
            "wIuhwy3IimZyZLlNKmZ4cXzC/qnZKEwTumTkDX0WQo3dRTGL+D+1CeuwuKIO2HeG\n" +
            "KjGCTWvw0xyP3IWDotEh9FJImV+9G0xKphMdfT5GJfj/+ix2J14qqvsZgQbLlHbo\n" +
            "S/kqwZOGZAwZywIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUw\n" +
            "AwEB/zAdBgNVHQ4EFgQU11VYe+bdyaYUH4MF8MFoJvdaOFkwHwYDVR0jBBgwFoAU\n" +
            "SeiFVAiLUuQQmUdIBKSGixMqCIkwDQYJKoZIhvcNAQELBQADggEBAIAEIodvCDnt\n" +
            "6R0OthdfOOgP9LNbkrvliitAiN4MO3U5WKvN9WAVreTMoeymYe5gpcZ/eEJHByWX\n" +
            "ocVN/U/dmMIAuloVknASYTijfcswYdqCHMvaBzXJyM9vZCp+TjLeyg3rpyJiru3E\n" +
            "Gfwrc9yzdvX0VOx8a4FBWIDr3/hrl829Re096Z8mVuBSyveF39URHuE+WWA+arPK\n" +
            "S1xt2nbN2Nfn7ZefcanuAmu6+0WnY4JAnyq9A4O4yrQAsRO8+2fTl7lNrOiyT28a\n" +
            "t1PtYLjhr0WTNDZvHhfwkolIwJJuirsLkZRuG4VAV2tJ3ZBypg6g1sY8zZDz3ZJJ\n" +
            "Id4Aht1VESg=\n" +
            "-----END CERTIFICATE-----";

    static final String TR34_KRD_CA_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEpAIBAAKCAQEAzSvOA0+tJ/h2/6mZQw/s/WckpTEu6dAmi9LqtaAZMdT+0bjc\n" +
            "PYKpLSFJ8l0p0lLOiv6OsEVdn7kb+N5hCOpsnV1gWW1L57VSpIdBlqdPD6PggUPs\n" +
            "lu+9gxDDbyCIrvET36W628Q2Q+nGwZV1muRU81SuR6G8Wopk2nruqLlTcR3+cnv6\n" +
            "83eQdsYvvq4mH0+wL4Sc3Se/wIuhwy3IimZyZLlNKmZ4cXzC/qnZKEwTumTkDX0W\n" +
            "Qo3dRTGL+D+1CeuwuKIO2HeGKjGCTWvw0xyP3IWDotEh9FJImV+9G0xKphMdfT5G\n" +
            "Jfj/+ix2J14qqvsZgQbLlHboS/kqwZOGZAwZywIDAQABAoIBAHu3NExu2PzHKApV\n" +
            "3CLCEadjcIdjtuQqLXQWxIysc0THKLiRfcxhY13hOtO4NaWrZPwPLz8/NItBdYqF\n" +
            "nYFgygnB6n1CGIkpnyGypWwQiu3lZVTM/natLVtA2nfB6GmE2PT83EX0dLxS1RSZ\n" +
            "6QZzNH5dy5FKB2eZF+NeSVbYGWaVGD9l7Uy5L87zFOtFUVUPan3ONPbh3sPZA6mL\n" +
            "4FvaOcuNyJp6L5rFXitEC+6JdZyXid4o8xfG4p8+0JqzuDaTsdzNPPjuFVkpxBLy\n" +
            "8mWtGwThwvjGzpvBc7P5a5p7IyYWDpCEP4EmtMwgbrySBpgPKx1nX48YRtNIg+GO\n" +
            "uLTTqbECgYEA9/kOXiO05d9LBJofg6bIF4YI5r+SaddM2uW350AVVBNNhysD9Ixp\n" +
            "zQb2/9iBIPW0CxW4q16DMUktkIz20VKAHe4KqktbotTXyEkjRM2PPrr2DOssWR+J\n" +
            "CxjRi7UzdAE4/ICNlo3g6TRWMT35Jv6n+oCbsYyi6Am7qqbE2YH6bAcCgYEA09AN\n" +
            "OjlmxzKtPqpXLbUyxoghMed8cvyJzxNcZV3jyLSXAcnVAgeH8tCsY5Nc5ecOUq36\n" +
            "Ety4vBaKVorolKtVLrBtA8floEBhWYpzax7VJ3OKq8GYbafDX+eF/pXmevwDVotB\n" +
            "Cvo/kQwaX7lwZS4sJ4k4CQ4WRaeTB3hE1Vxl+x0CgYEArawVUAGaFNVK6TI4mDAb\n" +
            "O754RYQuu0o7XaQ+JQxQ482RIvYRkxk0kJAsNgwghEERlCHmcL+FCuPBsdfIldo+\n" +
            "OLgbaCHXUDfZ2UDAHtQJW1n+MhYTvWfEx6zeNgb2vmyMyOwQPj2oJCyvoVVSRulc\n" +
            "JKomYTeqcPFAKskaXWwXQ8kCgYEA0gdWZmqu0E0e3qmX4nnvTE+F4u8wRvDFUbFY\n" +
            "CCeui8EOj7Zr4iRHmO10UxS3pDyVxkQ/WV7GS7NqH2CEOY8e2zoUDxCzUFEmdtxD\n" +
            "kG+1WvZGBgPkuq8Em19/Ta+kKEUmpjVVHKaCS7idmlfN7HZ5UAbPqqLuUMlWkKyg\n" +
            "TJTfhr0CgYAdqiZlltOz9pJ5ZBCtduuohIc9mc5lDRabeKn9SXhPBOYZu2U+e+7a\n" +
            "L6WIX2bTtVq6B5qVv08/frdrBh5gzDig+mTiQxs3oQqersj5Cab89ruHVSoBYglr\n" +
            "/Zawxw4blDLa/R507/ipeFF1Tl2fxdN3s79/GVuoRE0LPH7zWnBsmw==\n" +
            "-----END RSA PRIVATE KEY-----";

    public static final String TR34_KDH_1_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDcDCCAligAwIBAgIQEt6WKvHM910o6MgARZ8UyzANBgkqhkiG9w0BAQsFADBT\n" +
            "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2Vv\n" +
            "czEgMB4GA1UEAxMXVEVTVCBDbG92ZXIgVFIzNCBLREggQ0EwHhcNMjMwOTAxMjIw\n" +
            "MTQ1WhcNMzgwODE0MjIwMDA5WjBSMQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xv\n" +
            "dmVyMREwDwYDVQQLEwhkZXZpY2VvczEfMB0GA1UEAxMWVEVTVCBDbG92ZXIgVFIz\n" +
            "NCBLREggMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANG3eq/n2Y9N\n" +
            "W+unTuzDoCT9XrHmLMukpM4qL4NCaJgBS7lXpcMBc7s9I954aw0TUKWBYDtgF6gv\n" +
            "s8DfMYcULW0/sH0LGVGBQ/dwUWY6vgfNfSDhtjGqEnl/JA0lwioSb7ZbxJ8pTv1H\n" +
            "F69GaBzkvYAbDJUcgDR5bEhCBxpel/Go2OzG3HknfVy1zaAIe9Z4z3FZ6Gp1e203\n" +
            "YRJjuaEhei8WsnZeUo1gVH8p3xDs9TrQsJTsS4E3IZukwemXF2dKMKgDGbo89QIc\n" +
            "wriJRhsDPAjvdkwCryhjCthjT+CcYkeiihSuTkrZbqSB3xU9ZNikI2aOs0suN0HW\n" +
            "su1+ZQppHz0CAwEAAaNBMD8wDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAw\n" +
            "HwYDVR0jBBgwFoAUbeIyuJDjaE5J/WjddKCtqKMCQ4wwDQYJKoZIhvcNAQELBQAD\n" +
            "ggEBADD96Ckbo9UFvCjZb0fMUHBbwpbZVLze/LUwxuQ2NOMDLZsP6TDtMYXMeeWN\n" +
            "+/VpuAmPt/2TwshUA6xuCtxV0XySsxMAhy77csGmfsA1dr0plYiMfGz0o03a+fcm\n" +
            "eTSO3GgCf6nJoH7Dxhfb0m4+CYIVlbvXG/C2sak98/orhux9SmjkfJ3ZtY4fYbp+\n" +
            "QOsMGdM6TZdXwjuG3luEVwUqrxMqLHpgJnf2I8jP9cNRvMXE9npoSq5v1MfWo6LG\n" +
            "WcbRVOvHwGPSlDzX1wmg+r99viY2LuHvSMmS90fs+XlxKIWJDpd20vY2UQRNBOn/\n" +
            "x71vA+0//1su6sE0LtPenoz2eFQ=\n" +
            "-----END CERTIFICATE-----";

    static final String TR34_KDH_1_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEpAIBAAKCAQEA0bd6r+fZj01b66dO7MOgJP1eseYsy6Skziovg0JomAFLuVel\n" +
            "wwFzuz0j3nhrDRNQpYFgO2AXqC+zwN8xhxQtbT+wfQsZUYFD93BRZjq+B819IOG2\n" +
            "MaoSeX8kDSXCKhJvtlvEnylO/UcXr0ZoHOS9gBsMlRyANHlsSEIHGl6X8ajY7Mbc\n" +
            "eSd9XLXNoAh71njPcVnoanV7bTdhEmO5oSF6Lxaydl5SjWBUfynfEOz1OtCwlOxL\n" +
            "gTchm6TB6ZcXZ0owqAMZujz1AhzCuIlGGwM8CO92TAKvKGMK2GNP4JxiR6KKFK5O\n" +
            "StlupIHfFT1k2KQjZo6zSy43Qday7X5lCmkfPQIDAQABAoIBADUWazpISKyb+p7m\n" +
            "1XXd95YlhWknSUOrxARkbW6eyvdfrJmYdF+u6GsHiSLx/LdsokejPocJRjPPD4PN\n" +
            "fC4jj3ROYRDmVFxripcCmbh1OlGjVP+T45ki4lZbNvcVDde0nw7coCNiQ5qd+oLm\n" +
            "IcjeppHdRwwgENw3uI96F243b+M+U1bmeYucL5hYYIh0W4juRpiAQUqYDmNTtGt2\n" +
            "DUH+ivs5FxuMVs+k/JciVbaMiVr9hs/FFY1p9qdT3jyiIKNUI8ScoX8/cefzW+wL\n" +
            "wNIuyRvPhIE2mkEIRGt3UHZz3pOqpWz0Yr+eluNPi5kAB0aEFHsDkx7fLVhXTJCY\n" +
            "SR2KYQkCgYEA9e3Ml9vjm78j3M75OcXWNxTDhbueQ8I+b3jEHilIOwg0w3U6uQDq\n" +
            "sXu0LA8u7DRqdIxV4JWoQzfX8BE7FXaB6CCGZzk5NbJz9WOGYq7zIQvGvUw6OzYN\n" +
            "JmcJKFTbyJd7IU7A5S/vLu4S/8+aGVpHWUU4TNpmNEnrFPYShem46zcCgYEA2k4M\n" +
            "gCVPEMuV8G73bsuB26D25OBiW+DjCSE5QgeLhW2d+HA4RZLR+N6gja5ZdSRKfh6v\n" +
            "tD2Q18P1OYibQUcXXZirynxPIBKgMYzQkeqqLeXpDK9+dELI3JO8iyQc3Jqf0NiK\n" +
            "QXKK2MI3NsnDgrJ/jj26ysQSuZ3yo71DqbVTyysCgYEA8fVvyK0YB+ELyLB99kBW\n" +
            "HUU5hTbtZF8VDJl14vLc1O+i8fdBuklTnyFFR9/8W3rKjjaQO3Ei5ldoBhL93YUG\n" +
            "FLsDYUWkqtcTTYgI7MiR/p5Wf2IjHKR2VaUkFmE/B+E5zLBuCk+Z9MNZQAQh6fWv\n" +
            "ov3+gWaTDbj4KFxeJxCn1gsCgYANq6WMwMlau+T/0XMdNRFEt6e+XW7LYiHViIcV\n" +
            "Y3ORP3QNAroDYVZUx1w2gxyHAWbIzxMhrllLqbHJkIxoYhNMgSsA2xf5YjE16SOG\n" +
            "f7N4fFVDvhmlHimF5pp//BrylZw8b9L4ljurpz3d6HSd0p+6QJNZ7z1c8k8ngcqi\n" +
            "7f/5UQKBgQC+/nN7ErSzAY0t3IAbhG8SxKoUrsgU+5WFEDTCuO/qnvXXQIG1VZZv\n" +
            "SkXt/EdTUsepE9YNHTVFGsGYV+Ctu/lbwVfrssi78dCsCr6+hAA6NznG4f8RoYSJ\n" +
            "0HuR2t8TorC9akETtuE1AKXoofITZVx+OuSocIn7em+cLzuZ7+38MQ==\n" +
            "-----END RSA PRIVATE KEY-----";

    public static final String TR34_KDH_2_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDcTCCAlmgAwIBAgIRAOlCYfqGO4D4ER57Qy5tGwswDQYJKoZIhvcNAQELBQAw\n" +
            "UzELMAkGA1UEBhMCVVMxDzANBgNVBAoTBkNsb3ZlcjERMA8GA1UECxMIZGV2aWNl\n" +
            "b3MxIDAeBgNVBAMTF1RFU1QgQ2xvdmVyIFRSMzQgS0RIIENBMB4XDTIzMDkxODIw\n" +
            "MzYxNVoXDTM4MDgxNDIyMDAwOVowUjELMAkGA1UEBhMCVVMxDzANBgNVBAoTBkNs\n" +
            "b3ZlcjERMA8GA1UECxMIZGV2aWNlb3MxHzAdBgNVBAMTFlRFU1QgQ2xvdmVyIFRS\n" +
            "MzQgS0RIIDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCacdeuY7yK\n" +
            "Z8z33EqrrAxbdQLKvydy281qjLr9Rv5Gcf29m93WftqmDMSZF6buX8CGADRcU++f\n" +
            "17Ab2hXzkmnBItmnrs0bOtdXVqR3l4SaJM2V5fMYTFGJiBcrwdw3h/vAzU707ftb\n" +
            "3N04SJKR3xGqjCCqrDDKghiRkbLiOhi/oiDOAgXXZj4MM4x2/70Q6ikMSpLlsdix\n" +
            "yMnW8hmB5upBmodPV5Z0FAJu4lYwBNKpENz/34UEO9CwRje4lGfidmF7Zhg8G8HA\n" +
            "2BZIYRJqnoQRlJwIoR1+9/FAgEoKATEJV/x/4XxAnb7EtP29NlEhAUOEJufPGSpV\n" +
            "urhhRJeTJ4OHAgMBAAGjQTA/MA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAA\n" +
            "MB8GA1UdIwQYMBaAFG3iMriQ42hOSf1o3XSgraijAkOMMA0GCSqGSIb3DQEBCwUA\n" +
            "A4IBAQCE2+Bb/FzbnO15AJWoRpkJdLGdz3t+a4Q5eQEvSVTJHGR1lurjafn3RD3w\n" +
            "cRzfq1Y3iqIjgfwSdV7psM1hw2YD7z5Nm370YTNbox+QTNbyVQBWMh5X2ht2yR9G\n" +
            "tNU9MWMc75XIbU5dU2MdNmeIOx9Oco0NOfqAwmt3Bin7zlDTy3LMjSAjX8vut4Vm\n" +
            "G43iGj80kT3TIy4cAY+fA540ThdVl+n3+Ur3JfbcRMytbq+k2JIhBG1ec6o+6sxY\n" +
            "ZgGgDJhsPz1sQpgpsMfUwkZw80Jr4ZgZgm9KSkmHT5lCl1mbUHyJeXx9hof6Rd88\n" +
            "ZE5gnJg8yjk6rc2s6DIcTn1tEkTh\n" +
            "-----END CERTIFICATE-----\n";

    public static final String TR34_KDH_2_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEowIBAAKCAQEAmnHXrmO8imfM99xKq6wMW3UCyr8nctvNaoy6/Ub+RnH9vZvd\n" +
            "1n7apgzEmRem7l/AhgA0XFPvn9ewG9oV85JpwSLZp67NGzrXV1akd5eEmiTNleXz\n" +
            "GExRiYgXK8HcN4f7wM1O9O37W9zdOEiSkd8RqowgqqwwyoIYkZGy4joYv6IgzgIF\n" +
            "12Y+DDOMdv+9EOopDEqS5bHYscjJ1vIZgebqQZqHT1eWdBQCbuJWMATSqRDc/9+F\n" +
            "BDvQsEY3uJRn4nZhe2YYPBvBwNgWSGESap6EEZScCKEdfvfxQIBKCgExCVf8f+F8\n" +
            "QJ2+xLT9vTZRIQFDhCbnzxkqVbq4YUSXkyeDhwIDAQABAoIBAEHscgnIHMRfRkhO\n" +
            "Sbk5eRTYv1ZXfbkzRV1DsNVHpmXfZlW24FwcTawvKwPF6sU5Le6Ey9TVJyVtZYid\n" +
            "8FzFlEqSW6GNpZMH7L8lBpLdpAY/y1k+jCNFAFDaPDm7SAqUCsvjVt6Jbo9pmSvb\n" +
            "HmUReHL52T/AvBrUqTQJoveZoNK68cyq9Uz54oEvyt1WrU7zaNiFGpH90Q1Qhb2J\n" +
            "Nlpjihpc6syqluVruYND/bJm9DJGqMLdlS6uD6fXp5aCGfixwvndLq1h6TCzEXLf\n" +
            "HcL8elN60SIZXUKDKPEDIQQa9jzBx6eqThErCvr7lZ6+YNqIx4F+2nkJdoZCrXN5\n" +
            "9a+f7fECgYEAydySZAEN/bIUlwXvN04x675rJtc4ih++dUrT7QrLouzhMz4wdIwM\n" +
            "RnV3/i/vkQoec1zjI7VETKlfgRDlicFjgShiyz74KJrUxmgvrfQsgO9wkNKrtAsm\n" +
            "936Qizh5+3WjuAPf/xtZhk31NVDR8v5IJJEDl5Miv47MAJxiCv5rSvsCgYEAw923\n" +
            "lJYzgRjjKdBMOFNEliVsmWaPrnwQDKKtJ809dq5THYwK9/Taz5Xx2SQBWxZF06/Z\n" +
            "efW2IqhNAza4unyNmVTcKiKiy/ziZwLMVl5gBudzrFuVnxSaDd7kCAlL9dTJ17dq\n" +
            "sf2FadgmqCvIlCgpkodi+HSXfCYdJ4rViyg9g+UCgYA4h4WTbdwuLJ2pgWbxVPuT\n" +
            "6jp1oRXbUHJ0xGS+4CQQ10dlo0fMi5+wZ5sX2vK66luGsP+G829SDKiLK2Esh7TG\n" +
            "6blo85RpQprNiUW48EU6QlOCqwycmfbqnk36PvGiItqbYLJs7YrPmqtNp/lzlBQ9\n" +
            "8UJRQ0oa3PFyRlkKfR8s2wKBgHqmiYH7OI9b1UxmyoPu6KEZGFNLHShHOgmfiMzG\n" +
            "wflimluDSY8R/j9FhyfRWyP944X2tTmg+wfi2i7sAmuM+WKN+DxOaiFQ3zlgUDK5\n" +
            "cGqCXzYMN7phPUL4U1UQ9Ucgk7CIg8Cnn/ayyyo+GKFmMPo322r4H7A3ccRENQqq\n" +
            "DTNdAoGBALKefyenQOTgjdIXlDICTIM4VRAMzrGI43wnIPKE6DEZwxhzt0jE5NYu\n" +
            "jWpTbaTuduIC6/b0jbiIBDefrOh/Rw4iVicXxC4lJJCoLqrNdLBfqvt9JAvBndan\n" +
            "KlXNyoIMUktye1+fywLHfmU+k0tWMm2PacdD7V4aUpN3G1qQeIwt\n" +
            "-----END RSA PRIVATE KEY-----\n";

    public static final String TR34_KRD_1_Cert_Pem = "-----BEGIN CERTIFICATE-----\n" +
            "MIIDcDCCAligAwIBAgIQbCpMOGMtYO46ksi7B0ziSTANBgkqhkiG9w0BAQsFADBT\n" +
            "MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xvdmVyMREwDwYDVQQLEwhkZXZpY2Vv\n" +
            "czEgMB4GA1UEAxMXVEVTVCBDbG92ZXIgVFIzNCBLUkQgQ0EwHhcNMjMwOTAxMjIw\n" +
            "NjUwWhcNMzgwODE0MjIwMDA5WjBSMQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQ2xv\n" +
            "dmVyMREwDwYDVQQLEwhkZXZpY2VvczEfMB0GA1UEAxMWVEVTVCBDbG92ZXIgVFIz\n" +
            "NCBLUkQgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALhilgrs5YCt\n" +
            "DSiWa/Z/TX96qztN0dLlyh7rYimeBkEpEU4kJwWogRrt6CGIQ1+guSZLm4QtqWzn\n" +
            "bR72bDSJHLArnWi+Dx+9AHMK1AaZUrf75eC/yh5yV/sI0YFmnWp4DjV0AtGKgzDm\n" +
            "cjgQloIR2zrUrPXihXSUcwxJe0q/IqrMEdQ+morvZ2w+8Vlo1WszyvknhrCUWzKg\n" +
            "zf9DZ+9BG1fKREffS2SUruBHCFkQeXDFdP3d1RtgZznWGXQhwUXa5jkoFkR4jQYK\n" +
            "R8Lhj8v9YEbWcG8L7lOMkCZfRWeGzuQnjKRS9bx6D67gxvY2XJLbmfov4HNVkdxS\n" +
            "O68xEd8qI6UCAwEAAaNBMD8wDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAw\n" +
            "HwYDVR0jBBgwFoAU11VYe+bdyaYUH4MF8MFoJvdaOFkwDQYJKoZIhvcNAQELBQAD\n" +
            "ggEBAKdiYCU87sxKtldqs+4bNrSIXEwc/6XKCG2nCCToGNYOE2FApDWBZcOUcSEd\n" +
            "Lp0n7FEa/gLWVr5J/EOUkDp+5gAgmtbyvHptla8ThxVWPFHCXXbo4qlylfFwcXF1\n" +
            "OG8I+mwggUSh9DFoq27JUJApjaDcVyQ2Ywvdq0EcITYgrrZKZrqD7JYTEYmVXtKq\n" +
            "B4091HxtSM9vWophBudJDfK308x9fj+PM6AZqWRG7XCMShi3tVERiImTw0Pqn2/P\n" +
            "K0aEafxpvTRJh0kjsujX4HteBGXzLjjikfyjJKGz6Fyl5A8T9VAEFObqqZQ6Sa92\n" +
            "wMMs9Ow1xNvbr1cGImewoVhyBJU=\n" +
            "-----END CERTIFICATE-----";

    public static final String TR34_KRD_1_PrivateKey_Pem = "-----BEGIN RSA PRIVATE KEY-----\n" +
            "MIIEogIBAAKCAQEAuGKWCuzlgK0NKJZr9n9Nf3qrO03R0uXKHutiKZ4GQSkRTiQn\n" +
            "BaiBGu3oIYhDX6C5JkubhC2pbOdtHvZsNIkcsCudaL4PH70AcwrUBplSt/vl4L/K\n" +
            "HnJX+wjRgWadangONXQC0YqDMOZyOBCWghHbOtSs9eKFdJRzDEl7Sr8iqswR1D6a\n" +
            "iu9nbD7xWWjVazPK+SeGsJRbMqDN/0Nn70EbV8pER99LZJSu4EcIWRB5cMV0/d3V\n" +
            "G2BnOdYZdCHBRdrmOSgWRHiNBgpHwuGPy/1gRtZwbwvuU4yQJl9FZ4bO5CeMpFL1\n" +
            "vHoPruDG9jZcktuZ+i/gc1WR3FI7rzER3yojpQIDAQABAoIBADJnKLLl3TrWk2FD\n" +
            "9VFVrV6qrsIwXKo1DJJ1L8lGnFkVm9hrg4tFa71ryWfZMumiKtqwElwIi2bswGSV\n" +
            "YjDeRkxWL9phEgtQBB5umFURdo46urU8WEkIYsqJt5OS9HcVSHUOOHMFVSV56UEw\n" +
            "L6Rwsyga2QkCGg8rQWPbdmuRYi2j0j95IFvszn7kzQZ6hcoEdbhedYX85Ij4mgR7\n" +
            "ydeli6SAMQ8dRIbsOFhdf07DvA5st59lRTDeC/kyYMN6SZHRl7Vr9cvsTVawJb7v\n" +
            "v94Q3fRqzq9rB/JdHjVjjx+NM97sc7azZFFFVtrnlOG80k4lMIZLnjH0ZMpXrkY6\n" +
            "4Vv7p6UCgYEA5uLIa9+vopgpgTR4CUmqAcDh6EAzAOyIRTxag5c0i2Tz+x4ffc2Y\n" +
            "6s7Rs9x1b8ypr+z8GKmsjhEyxlToFEG0cZTBQzQEMsQ89jJbbLz8pSglS1hM3W4Y\n" +
            "zDGhiBtiJRpvuA3ZJN0No09cYDbH/y5ZyM6AAgwK1uD0vu5eTvoP83MCgYEAzHDy\n" +
            "8rVoHfF82pHrmzz8NRhf8SuDI+rwm+ThDnphteMXmJSz9ki8lljaF2T/mMsCHn1B\n" +
            "o+R5WTg1b/0+YGEH7OAjKNx+6K7BCZ1dA5S+dHtZjCvp2Bp3UL7FtK3dptQEL3t+\n" +
            "0SnSFBZ9lpXLj8dQNTwISVM8LD7vOBtVAOZftocCgYApFqzSPcGU7v1b6AmApaJi\n" +
            "o3/QhDRPcsihgaceCfeo4vNkeizih4cyKlI5bv9bQRHlpAgNH4z8z2S41P1kNXk2\n" +
            "SWHHYudoXXH34mhQxqUzgxx39yPeuCwjkqWLgkwKDFVbbON64vf9Wy82VCltaUND\n" +
            "MDSpqJj5OplzrRoNdgUGrwKBgEPHrsSJIFvNFHfiqRpuva9cxXJP2sqtudf1qigC\n" +
            "qyKCh/AuXPvqYZv3GVdoRNWDeNBi9sA/n3vVBuJ6M5QAl4ART5bcg7bhOV7WrV/i\n" +
            "kMJNowK2DHF5VNWQajvc6P/Gixyy9PijxOKkEj86qqKgkhcUMCsfTXPd6bHQXf5O\n" +
            "Yq1BAoGAaYsPFFv1uZJSDLb4kd5wW1o2AV2a5PhKqn71dCvYal6Dtm66jQnSvWSN\n" +
            "Jo7ewgPInB6FGUiHkG0uxCDaWxbqMoX0Gv6qhXP70TNg6PxTFZYQIcMOtjMWtfbo\n" +
            "JJbzKc5rgdHayNGWor9LWY7Y3gFASuItLuHLyI8n8Xx/zuaLxv8=\n" +
            "-----END RSA PRIVATE KEY-----";

    private final X509Certificate rootCert;
    private final X509Certificate krdCaCert;
    private final X509Certificate kdhCaCert;
    private final X509Certificate kdhCert;

    private final PrivateKey krdCaPrivateKey;
    private final PrivateKey kdhCaPrivateKey;
    private final PrivateKey kdhPrivateKey;

    private final List<X509Certificate> kdhIssuerChain;

    private CloverSampleTr34KeyStoreData(String kdhCertPem, String kdhPrivateKeyPem, String... kdhIssuerChainPem) {
        kdhCert = Tr34CryptoUtils.parseCert(kdhCertPem);
        kdhPrivateKey =  Tr34CryptoUtils.parsePrivateKey(kdhPrivateKeyPem);

        rootCert = Tr34CryptoUtils.parseCert(TR34_Root_Cert_Pem);
        kdhCaCert = Tr34CryptoUtils.parseCert(TR34_KDH_CA_Cert_Pem);
        krdCaCert = Tr34CryptoUtils.parseCert(TR34_KRD_CA_Cert_Pem);

        kdhCaPrivateKey = Tr34CryptoUtils.parsePrivateKey(TR34_KDH_CA_PrivateKey_Pem);
        krdCaPrivateKey = Tr34CryptoUtils.parsePrivateKey(TR34_KRD_CA_PrivateKey_Pem);

        List<X509Certificate> kdhChain = new LinkedList<>();
        for (String certPem : kdhIssuerChainPem) {
            kdhChain.add(Tr34CryptoUtils.parseCert(certPem));
        }

        kdhIssuerChain = Collections.unmodifiableList(kdhChain);

        verifyKdh();
        verifyKrdCa();
    }

    public static final Tr34KeyStoreData KDH_1 =
            new CloverSampleTr34KeyStoreData(TR34_KDH_1_Cert_Pem, TR34_KDH_1_PrivateKey_Pem, TR34_KDH_CA_Cert_Pem, TR34_Root_Cert_Pem);

    public static final Tr34KeyStoreData KDH_2 =
            new CloverSampleTr34KeyStoreData(TR34_KDH_2_Cert_Pem, TR34_KDH_2_PrivateKey_Pem, TR34_KDH_CA_Cert_Pem, TR34_Root_Cert_Pem);

    @Override
    public X509Certificate getRootCert() {
        return rootCert;
    }

    @Override
    public List<X509Certificate> getKdhIssuerChain() {
        return kdhIssuerChain;
    }

    @Override
    public X509Certificate getKdhCert() {
        return kdhCert;
    }

    @Override
    public X509Certificate getKrdCaCert() {
        return krdCaCert;
    }

    @Override
    public Tr34ScdKeyStoreData getKdhKeyStoreData() {
        return new Tr34ScdKeyStoreData(kdhCert, kdhPrivateKey);
    }

    @Override
    public Tr34ScdKeyStoreData getKdhCaKeyStoreData() {
        return new Tr34ScdKeyStoreData(kdhCaCert, kdhCaPrivateKey);
    }

    @Override
    public Tr34ScdKeyStoreData getKrdCaKeyStoreData() {
        return new Tr34ScdKeyStoreData(krdCaCert, krdCaPrivateKey);
    }

    @Override
    public List<Tr34KdhRevocation> getKdhRevocationList() {
        // Sample revoked cert
        return Collections.singletonList(new Tr34KdhRevocation(BigInteger.valueOf(1300000L),
                new Date(1699743671000L), CRLReason.CESSATION_OF_OPERATION));
    }

    @Override
    public int nextCrlUpdateDays() {
        return 30;
    }
}
